blender-bfct/application/models/applications.py
import datetime
from application import app, db
from application.helpers import pretty_date
from users import User

from sqlalchemy.ext.associationproxy import association_proxy
from flask.ext.security import current_user


class Application(db.Model):
    __table_args__ = {'schema': 'blender-bfct'}
    id = db.Column(db.Integer(), primary_key=True)
    #blender_id = db.Column(db.Integer(), db.ForeignKey(User.id), nullable=False)
    #user = db.relationship('User')
    blender_id = db.Column(db.Integer(), nullable=False)
    network_profile = db.Column(db.String(255))
    website = db.Column(db.String(255))
    city_country = db.Column(db.String(255))
    institution_name = db.Column(db.String(255))
    skills = db.relationship('Skill', secondary='skills_applications',
                            backref=db.backref('applications', lazy='dynamic', cascade='all'))
    video_example = db.Column(db.String(255))
    written_example = db.Column(db.String(255))
    portfolio_cv = db.Column(db.String(255))
    bio_message = db.Column(db.Text())
    submission_date = db.Column(db.DateTime(), default=datetime.datetime.now)
    status = db.Column(db.String(255))
    approve = db.Column(db.Integer(), default=0)
    reject = db.Column(db.Integer(), default=0)
    review_start_date = db.Column(db.DateTime())
    review_end_date = db.Column(db.DateTime())
    renewal_date = db.Column(db.DateTime())

    #reviewers = db.relationship('ReviewersApplications', backref=db.backref('reviewers', cascade='all'))

    def show_pretty_date(self, stage_date):
        if stage_date == 'submission':
            return pretty_date(self.submission_date)
        elif stage_date == 'review_start':
            return pretty_date(self.review_start_date)
        elif stage_date == 'review_end':
            return pretty_date(self.review_end_date)
        else:
            return '--'

    def is_reviewed(self):       
        for review in ReviewersApplications.query.\
            filter_by(application_id=self.id).\
            all():
            if review.reviewer_blender_id == current_user.id:
                return True
        return False

    @property
    def user(self):
        return User.query.get_or_404(self.blender_id)



class Skill(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(255))
    
    def __str__(self):
        return self.name



skills_applications = db.Table('skills_applications',
        db.Column('application_id', db.Integer(), db.ForeignKey(Application.id)),
        db.Column('skill_id', db.Integer(), db.ForeignKey('skill.id')))


class ReviewersApplications(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    application_id = db.Column(db.Integer(), db.ForeignKey(Application.id), nullable=False)
    application = db.relationship('Application', backref=db.backref('reviewers', cascade='all'))
    #reviewer_blender_id = db.Column(db.Integer(), db.ForeignKey(User.id), nullable=False)
    #reviewer = db.relationship('User')
    reviewer_blender_id = db.Column(db.Integer(), nullable=False)
    approved = db.Column(db.Boolean(), nullable=False)

    @property
    def reviewer(self):
        return User.query.get_or_404(self.reviewer_blender_id)


class Comment(db.Model):
    """Comments to an application. Only BFCT board members can add comments
    via the applications review inferface"""

    id = db.Column(db.Integer(), primary_key=True)

    application_id = db.Column(db.Integer(), db.ForeignKey(Application.id), nullable=False)
    application = db.relationship('Application', backref=db.backref('comments', cascade='all'))

    blender_id = db.Column(db.Integer(), nullable=False)
    text = db.Column(db.Text())
    creation_date = db.Column(db.DateTime(), default=datetime.datetime.now)


    @property
    def pretty_creation_date(self):
        return pretty_date(self.creation_date)

    @property
    def user(self):
        return User.query.get_or_404(self.blender_id)

blender-bfct/application/controllers/applications.py
import datetime
from dateutil.relativedelta import relativedelta
from sqlalchemy import desc

from application import db
from application.forms  import CommentForm
from application.forms  import ApplicationStatusForm
from application.models.users import *
from application.models.applications import Application, Skill, ReviewersApplications, Comment

from flask import render_template, redirect, url_for, request, Blueprint, abort
from flask.ext.security import login_required, roles_accepted
from flask.ext.security.core import current_user



applications = Blueprint('applications', __name__)

@applications.route('/')
@roles_accepted('bfct_board', 'bfct_manager', 'admin')
def index():
    return render_template('applications/index.html', 
        title='applications',
        applications=Application.query.order_by(desc('submission_date')).all())

@applications.route('/view/<int:id>')
@login_required
@roles_accepted('bfct_board', 'bfct_manager', 'admin')
def view(id):
    application = Application.query.get_or_404(id)
    comment_form = CommentForm()
    application_status_form = ApplicationStatusForm(
        status=application.status)

    review = ReviewersApplications.query.\
        filter_by(application_id=id).\
        filter_by(reviewer_blender_id=current_user.id).\
        first()

    reviews = ReviewersApplications.query.\
        filter_by(application_id=id).\
        all()

    return render_template('applications/view.html', 
        title='applications',
        application=application,
        review=review,
        reviews=reviews,
        comment_form=comment_form,
        application_status_form=application_status_form)

@applications.route('/vote/<int:approved>/<int:id>')
@roles_accepted('bfct_board', 'bfct_manager', 'admin')
def vote(approved, id):
    application = Application.query.get_or_404(id)
    review = ReviewersApplications.query.\
        filter_by(application_id=id).\
        filter_by(reviewer_blender_id=current_user.id).\
        first()

    if approved:
        if review:
            application.reject -= 1
        application.approve += 1
    else:
        if review:
            application.approve -= 1
        application.reject += 1

    if application.status == 'submitted':
        application.status = 'under_review'
        application.review_start_date = datetime.datetime.now()
    db.session.add(application)

    if not review:
        review = ReviewersApplications(
            application_id=id,
            reviewer_blender_id=current_user.id,
            approved=approved) 
    else:
        review.approved = approved

    db.session.add(review)
    
    db.session.commit()
    return redirect(url_for('.view', id=id))

@applications.route('/final-review/<int:approved>/<int:id>')
@roles_accepted('bfct_manager', 'admin')
def final_review(approved, id):
    application = Application.query.get_or_404(id)
    if application.status in ['under_review', 'pending']:
        if approved:
            application.status = 'approved'
        else:
            application.status = 'rejected'
        review_end_date = datetime.datetime.now()
        application.review_end_date = review_end_date
        application.renewal_date = review_end_date + relativedelta(years=1)
        db.session.add(application)
   
        db.session.commit()
    else:
        return abort(404)
    return redirect(url_for('.view', id=id))


@applications.route('/comment/<int:application_id>', methods=['POST'])
@roles_accepted('bfct_board', 'bfct_manager', 'admin')
def comment(application_id):
    comment_form = CommentForm()
    if comment_form.validate_on_submit():
        comment = Comment(
            blender_id=current_user.id,
            application_id=application_id,
            text=comment_form.text.data)

        db.session.add(comment)
        db.session.commit()
    return redirect(url_for('.view', id=application_id))


@applications.route('/edit/<int:application_id>/update-bfct-role/')
@roles_accepted('bfct_manager', 'admin')
def update_bfct_role(application_id):
    application = Application.query.get_or_404(application_id)
    user = User.query.get_or_404(application.blender_id)
    applications = Application.query\
        .filter_by(blender_id=user.id)\
        .all()

    for application in applications:
        if application.status == 'approved':
            # TODO: additional check to see if application is valid
            user_datastore.add_role_to_user(user, 'bfct_trainer')
            db.session.commit()
        else:
            user_datastore.remove_role_from_user(user, 'bfct_trainer')
            db.session.commit()
    return redirect(url_for('.view', id=application_id))


@applications.route('/edit/<int:application_id>/status/<status>')
@roles_accepted('bfct_manager', 'admin')
def set_status(application_id, status):
    application = Application.query.get_or_404(application_id)
    application.status = status

    db.session.commit()
    return 'ok'

blender-bfct/application/templates/applications/index.html
{% extends 'layout.html' %}
{% block page_title %}BFCT Applications{% endblock %}
{% block body %}
<div class="row">
    <div class="col-md-12">
        <h1>BFCT Applications</h1>
        <table class="table table-striped box">
            <thead>
                <tr>
                    <th class="content-margin-center">#</th>
                    <th>Name</th>
                    <th>Country</th>
                    <th>Submitted On</th>
                    <th>Status</th>
                    <th class="content-margin-center">Voted</th>
                    <th class="content-margin-center">Approvals</th>
                </tr>
            </thead>
            <tbody>
            {% for application in applications %}
                <tr class="{% if not application.is_reviewed() %}danger{% endif %} table-row-link" link="{{url_for('applications.view', id=application.id)}}">
                    <td class="relative content-margin-center">{{ application.id }}</td>
                    <td>
                        {{application.user.first_name}} {{application.user.last_name}}
                    </td>
                    <td>{{application.city_country}}</td>
                    <td>{{application.submission_date.strftime('%d %B, %Y')}}</td>
                    <td>
                        <a href="{{url_for('applications.view', id=application.id)}}" >
                    {% if application.status == 'under_review' %}
                        <span class="label label-2x label-info"><i class="fa fa-clock-o"></i> Under Review</span>
                    {% elif application.status == 'submitted' %}
                        <span class="label label-2x label-danger"><i class="fa fa-warning"></i> Pending</span>
                    {% elif application.status == 'approved' %}
                        <span class="label label-2x label-success"><i class="fa fa-check"></i> Approved!</span>
                    {% elif application.status == 'rejected' %}
                        <span class="label label-2x label-default"><i class="fa fa-times"></i> Rejected</span>
                    {% else %}
                        {{application.status}}
                    {% endif %}
                        </a>
                    </td>
                    <td class="content-margin-center">
                        {% if application.is_reviewed() %}
                            <i class="fa fa-check" title="You voted for this applicant"></i>
                        {% else %}
                            <i class="fa fa-times" title="You haven't voted yet, tsk!"></i>
                        {% endif %}
                    </td>
                    <td class="content-margin-center">
                        {{application.approve}}
                            /
                        {{application.approve + application.reject}}
                    </td>
                </tr>
                {% if loop.last %}
                </tbody>
            </table>
                <div class="content-align-right">
                    Listing {{ loop.index }} applications
                </div>
                {% endif %}
            {% endfor %}
    </div>
</div>
<hr/>

{% endblock %}

{% block footer_scripts %}
<script type="text/javascript">
  $(".table-row-link").on("click", function() {
      window.location.href = $(this).attr('link');
  });

</script>

{% endblock %}

blender-bfct/application/templates/applications/view.html
{% extends 'layout.html' %}
{% block page_title %}{{application.user.first_name}}'s BFCT Application{% endblock %}
{% block body %}
<div class="row">
    <div class="col-md-8">
        {% if application.user.first_name %}
            <h1>{{application.user.first_name}} {{application.user.last_name}}</h1>
        {% else %}
            <h1>{{application.user.email}}</h1>
        {% endif %}
                
        <h4><i class="fa fa-map-marker"></i> {{application.city_country}}</h4>
        <p>{{application.bio_message|safe}}</p>
        <div class="box">
            <i class="backicon fa fa-info-circle"></i>
        <p>
         <h3>{{application.user.first_name}}'s details:</h3>
         <ul class="list-margin-none margin-top-1">
            {% if current_user.has_role('admin') %}
            <li>Email:
                <a href="mailto:{{application.user.email}}">
                    {{application.user.email}}
                </a>
            </li>
            {% endif %}
            <li>Website:
                <a href="{{application.website}}">
                    {{application.website}}
                </a>
            </li>
            <li>Portfolio: 
                <a href="{{application.portfolio_cv}}">
                    {{application.portfolio_cv}}
                </a>
            </li>
            <li>Video Example:
                <a href="{{application.video_example}}">
                    {{application.video_example}}
                </a>
            </li>
            <li>Written Example:
                <a href="{{application.written_example}}">
                    {{application.written_example}}
                </a>
            </li>
        </ul>
    </p>
        </div>
    </div>
    <div class="col-md-4">
        <h3>Application Status</h3>
        {% if current_user.has_role('admin') %}
        <div class="row jobs-admin">
            <div class="col-md-6 col-sm-6 col-xs-6">
                Job Status:
            </div>
            <div class="col-md-6 col-sm-6 col-xs-6">
                {{ application_status_form.status }}
            </div>
        </div>
        {% endif %}
        <div class="box">
            {% if application.status == 'under_review' %}
                <i class="backicon fa fa-clock-o"></i>
                <h1>Under Review <i class="title-icon fa fa-clock-o"></i></h1>
            {% elif application.status == 'submitted' %}
                <i class="backicon fa fa-legal"></i>
                <h1>Pending Review <span class="danger pull-right"><i class="fa fa-legal"></i></span></h1>
            {% elif application.status == 'approved' %}
                <i class="backicon fa fa-star"></i>
                <h1>Approved! <span class="warning pull-right"><i class="fa fa-star"></i>
                </span></h1>
            {% elif application.status == 'rejected' %}
                <i class="backicon fa fa-times"></i>
                <h1>Rejected <span class="danger pull-right"><i class="fa fa-times"></i>
                </i></h1>
            {% else %}
                {{application.status}}
            {% endif %}
            <p>Submitted <span title="{{application.submission_date.strftime('%A %d %B, %Y @ %H:%m')}}">{{application.show_pretty_date('submission')}}</span>.</p>
        {% if review %}
        <p>
            <i class="fa fa-info-circle margin-top-2 margin-left-1 margin-right-1"></i>
            You {% if review.approved %}
                <strong class="success"> approved </strong>
                {% else %}
                <strong class="danger"> rejected </strong>
                {% endif %} this candidate.
        </p>
        <hr/>
        {% endif %}
        <div class="row">
            <div class="col-md-12">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Reviewer</th>
                            <th class="content-margin-center">Verdict</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if reviews %}
                            {% for review in reviews%}
                            <tr>
                                <td>
                                {% if review.reviewer.id == current_user.id %}
                                    <strong>
                                {% endif %}
                                {{review.reviewer.first_name}} {{review.reviewer.last_name}}
                                {% if review.reviewer.id == current_user.id %}
                                    </strong>
                                {% endif %}
                                </td>
                                <td class="content-margin-center">
                                {% if review.approved %}
                                    <i class="fa fa-check success"></i>
                                {% else %}
                                    <i class="fa fa-times danger"></i>
                                {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                        {% else %}
                        <tr>
                            <td class="danger">
                                <i class="fa fa-warning"></i> Tsk tsk! Nobody reviewed this yet.
                            </td>
                            <td></td>
                        </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
        </div>
        {% if not review %}
        <hr/>
        <div class="row">
            <div class="col-md-6">
                <a href="{{url_for('applications.vote', approved=1, id=application.id)}}" class="btn btn-default btn-block btn-squishy btn-success">
                    <i class="fa fa-thumbs-up"></i> Approve
                </a>
            </div>
            <div class="col-md-6">
                <a href="{{url_for('applications.vote', approved=0, id=application.id)}}" class="btn btn-default btn-block btn-squishy btn-danger">
                    <i class="fa fa-thumbs-down"></i> Reject
                </a>
            </div>
        </div>
        {% endif %}
        {% if current_user.has_role('admin') %}
        <hr/>
        <div class="row">
            <div class="col-md-12">
                <a href="{{url_for('applications.update_bfct_role', application_id=application.id)}}" class="btn btn-default btn-block btn-squishy btn-default">
                    <i class="fa fa-refresh"></i> Update BFCT Role
                </a>
            </div>
        </div>
        {% endif %}
        <div class="row">
            <div class="col-md-12">
                <hr>
                <h2>Comments
                {% if application.comments %}
                    {% for comment in application.comments %}
                        {% if loop.first %}
                            <div class="pull-right">
                                ({{ loop.length }})
                            </div>
                        {% endif %}
                        </h2>
                        <div class="box margin-bottom-2">

                            <span class="pull-right small"><p><small>{{comment.pretty_creation_date}} <i class="fa fa-clock-o"></i></small></p></span>
                            <span><h4 class="margin-top-3">{{comment.user.first_name}} {{comment.user.last_name}}</h4></span>
                            <hr class="margin-top-0 margin-bottom-0"/>
                            <p>{{comment.text}}</p>
                        </div>
                    {% endfor %}
                {% else %}
                    </h2>
                {% endif %}

                <form class="form-horizontal margin-bottom-15px" method="POST" action="{{url_for('applications.comment', application_id=application.id)}}">
                    <fieldset>
                        {{ comment_form.hidden_tag() }}
                        <div class="input-group input-group-lg width-full">
                            {{ comment_form.text(class="form-control") }}
                            <label class="control-label">Leave a comment</label>
                        </div>
                        <button class="btn btn-default btn-squishy btn-success width-half pull-right margin-top-2" type="submit" value="Go">
                            Submit Comment <i class="fa fa-send small"></i>
                        </button>
                    </fieldset>
                </form>
            </div>
        </div>
        </div>
        {% if current_user.has_role('admin') %}
            {% if not application.review_end_date %}
                <div class="col-md-12"><hr/></div>

                <div class="col-md-6">
                    <a href="{{url_for('applications.final_review', approved=1, id=application.id)}}" class="btn btn-default btn-block btn-squishy btn-success"><i class="fa fa-check"></i> Final Approval</a>       
                </div>
                <div class="col-md-6 margin-bottom-15px">
                    <a href="{{url_for('applications.final_review', approved=0, id=application.id)}}" class="btn btn-default btn-block btn-squishy btn-danger"><i class="fa fa-times"></i> Final Rejection</a>       
                </div>
            {% endif %}
        {% endif %}
    </div>
</div>

{% endblock %}

{% block footer_scripts %}
<script type="text/javascript">
    $(document).ready(function() {
    {% if current_user.has_role('admin') %}
        $( "#set_status" ).change(function() {
            $.get( "{{config.SUBFOLDER}}" + "/applications/edit/" + {{application.id}} + "/status/" + $(this).val());
            console.log($(this).val());
        });
    {% endif %}
    });
</script>
{% endblock %}