blender-bfct/application/controllers/applications.py
import datetime
from dateutil.relativedelta import relativedelta
from sqlalchemy import desc

from application import db
from application.forms  import CommentForm
from application.forms  import ApplicationStatusForm
from application.models.users import *
from application.models.applications import Application, Skill, ReviewersApplications, Comment

from flask import render_template, redirect, url_for, request, Blueprint, abort
from flask.ext.security import login_required, roles_accepted
from flask.ext.security.core import current_user



applications = Blueprint('applications', __name__)

@applications.route('/')
@roles_accepted('bfct_board', 'bfct_manager', 'admin')
def index():
    return render_template('applications/index.html', 
        title='applications',
        applications=Application.query.order_by(desc('submission_date')).all())

@applications.route('/view/<int:id>')
@login_required
@roles_accepted('bfct_board', 'bfct_manager', 'admin')
def view(id):
    application = Application.query.get_or_404(id)
    comment_form = CommentForm()
    application_status_form = ApplicationStatusForm(
        status=application.status)

    review = ReviewersApplications.query.\
        filter_by(application_id=id).\
        filter_by(reviewer_blender_id=current_user.id).\
        first()

    reviews = ReviewersApplications.query.\
        filter_by(application_id=id).\
        all()

    return render_template('applications/view.html', 
        title='applications',
        application=application,
        review=review,
        reviews=reviews,
        comment_form=comment_form,
        application_status_form=application_status_form)

@applications.route('/vote/<int:approved>/<int:id>')
@roles_accepted('bfct_board', 'bfct_manager', 'admin')
def vote(approved, id):
    application = Application.query.get_or_404(id)
    review = ReviewersApplications.query.\
        filter_by(application_id=id).\
        filter_by(reviewer_blender_id=current_user.id).\
        first()

    if approved:
        if review:
            application.reject -= 1
        application.approve += 1
    else:
        if review:
            application.approve -= 1
        application.reject += 1

    if application.status == 'submitted':
        application.status = 'under_review'
        application.review_start_date = datetime.datetime.now()
    db.session.add(application)

    if not review:
        review = ReviewersApplications(
            application_id=id,
            reviewer_blender_id=current_user.id,
            approved=approved) 
    else:
        review.approved = approved

    db.session.add(review)
    
    db.session.commit()
    return redirect(url_for('.view', id=id))

@applications.route('/final-review/<int:approved>/<int:id>')
@roles_accepted('bfct_manager', 'admin')
def final_review(approved, id):
    application = Application.query.get_or_404(id)
    if application.status in ['under_review', 'pending']:
        if approved:
            application.status = 'approved'
        else:
            application.status = 'rejected'
        review_end_date = datetime.datetime.now()
        application.review_end_date = review_end_date
        application.renewal_date = review_end_date + relativedelta(years=1)
        db.session.add(application)
   
        db.session.commit()
    else:
        return abort(404)
    return redirect(url_for('.view', id=id))


@applications.route('/comment/<int:application_id>', methods=['POST'])
@roles_accepted('bfct_board', 'bfct_manager', 'admin')
def comment(application_id):
    comment_form = CommentForm()
    if comment_form.validate_on_submit():
        comment = Comment(
            blender_id=current_user.id,
            application_id=application_id,
            text=comment_form.text.data)

        db.session.add(comment)
        db.session.commit()
    return redirect(url_for('.view', id=application_id))


@applications.route('/edit/<int:application_id>/update-bfct-role/')
@roles_accepted('bfct_manager', 'admin')
def update_bfct_role(application_id):
    application = Application.query.get_or_404(application_id)
    user = User.query.get_or_404(application.blender_id)
    applications = Application.query\
        .filter_by(blender_id=user.id)\
        .all()

    for application in applications:
        if application.status == 'approved':
            # TODO: additional check to see if application is valid
            user_datastore.add_role_to_user(user, 'bfct_trainer')
            db.session.commit()
        else:
            user_datastore.remove_role_from_user(user, 'bfct_trainer')
            db.session.commit()
    return redirect(url_for('.view', id=application_id))


@applications.route('/edit/<int:application_id>/status/<status>')
@roles_accepted('bfct_manager', 'admin')
def set_status(application_id, status):
    application = Application.query.get_or_404(application_id)
    application.status = status

    db.session.commit()
    return 'ok'

blender-bfct/application/templates/apply.html
{% extends 'layout.html' %}
{% block page_title %}Submit Application{% endblock %}
{% block body %}
<div class="row">
    <div class="col-md-8">
        <div class="container-fluid">
            <h2>Submit your Application</h2>
            <hr/>
            <form class="form-horizontal" method="POST" action="{{url_for('apply')}}">
                <fieldset>
                    {{ form.hidden_tag() }}
                    <div class="input-group input-group-lg width-full">
                        <span class="input-group-addon"><i class="bf-network"></i></span>
                        {{ form.network_profile(class='form-control', placeholder='e.g. http://blendernetwork.org/<name-surname>') }} 
                        <label class="control-label">Blender Network Profile (optional)</label>
                    </div>

                    <div class="input-group input-group-lg width-full">
                        <span class="input-group-addon"><i class="fa fa-globe"></i></span>
                        {{ form.website(class='form-control', placeholder='e.g. http://www.yourname.me') }} 
                        {% if form.website.errors %}
                            <ul class="danger list-margin-none list-bullets-none padding-left-0 text-align-right">
                                {% for error in form.website.errors %}<li>{{ error }}</li>{% endfor %}
                            </ul>
                        {% endif %}
                        <label class="control-label">Website</label>
                    </div>

                    <div class="input-group input-group-lg width-full">
                        <span class="input-group-addon"><i class="fa fa-map-marker"></i></span>
                        {{ form.city_country(class='form-control', placeholder='Where do you currently live/teach?') }}
                        {% if form.city_country.errors %}
                            <ul class="danger list-margin-none list-bullets-none padding-left-0 text-align-right">
                                {% for error in form.city_country.errors %}<li>{{ error }}</li>{% endfor %}
                            </ul>
                        {% endif %}
                        <label class="control-label">City and Country</label>
                    </div>

                    <hr/>

                    <div class="row">
                        <div class="col-md-6">
                            <p class="margin-top-4">
                            Are you currently teaching at an institution?
                            </p>
                        </div>
                        <div class="col-md-6">
                         <div class="input-group input-group-lg width-full" id="is_teaching_where">
                            {{ form.institution_name(class="form-control", placeholder="University / School / Institution's name") }}
                            <label class="control-label">School or Institution Name</label>
                         </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <p class="margin-top-4">
                            Select which skills you focus on for teaching.
                            <br/>
                            <small>(hold Ctrl for multiple selections)</small>
                            </p>
                        </div>
                        <div class="col-md-6">
                         <div class="input-group input-group-lg width-full">
                            {{ form.skills(class='form-control') }}
                            <label class="control-label">Areas of Expertise</label>
                         </div>
                        </div>
                    </div>

                    <hr/>

                    <div class="row">
                        <div class="col-md-6">
                            <p class="margin-top-4">
                            Provide a video (or a list of videos) that show your
                            talking and training skills at their best.
                            </p>
                        </div>
                        <div class="col-md-6">
                         <div class="input-group input-group-lg width-full">
                            <span class="input-group-addon"><i class="fa fa-file-video-o"></i></span>
                            {{ form.video_example(class='form-control', placeholder='URL to a Video Example') }}
                            {% if form.video_example.errors %}
                                <ul class="danger list-margin-none list-bullets-none padding-left-0 text-align-right">
                                    {% for error in form.video_example.errors %}<li>{{ error }}</li>{% endfor %}
                                </ul>
                            {% endif %}
                            <label class="control-label">Video Example</label>
                         </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <p class="margin-top-4">
                            Link us a tutorial (or a list/guide) that show your
                            writing skills at their best.
                            </p>
                        </div>
                        <div class="col-md-6">
                         <div class="input-group input-group-lg width-full">
                            <span class="input-group-addon"><i class="fa fa-file-text-o"></i></span>
                            {{ form.written_example(class='form-control', placeholder='URL to a Written Example') }}
                            {% if form.written_example.errors %}
                                <ul class="danger list-margin-none list-bullets-none padding-left-0 text-align-right">
                                    {% for error in form.written_example.errors %}<li>{{ error }}</li>{% endfor %}
                                </ul>
                            {% endif %}
                            <label class="control-label">Written Example</label>
                         </div>
                        </div>
                    </div>

                    <div class="col-md-12 box margin-top-2 alert-info">
                        <p><i class="fa fa-info-circle"></i>
                        <small>The language for both the written/spoken tutorial(s) is up to you, but bare in mind it might require more time for us to review if it's not among the board's native languages.</small>
                        </p>
                    </div>

                    <hr/>

                     <div class="input-group input-group-lg width-full">
                        {{ form.portfolio_cv(class='form-control', placeholder='URL of your Portfolio or CV. e.g: http://yourportfolio.me') }}
                        {% if form.portfolio_cv.errors %}
                            <ul class="danger list-margin-none list-bullets-none padding-left-0 text-align-right">
                                {% for error in form.portfolio_cv.errors %}<li>{{ error }}</li>{% endfor %}
                            </ul>
                        {% endif %}
                        <label class="control-label">Porftolio / Curriculum Vitae</label>
                     </div>

                    <hr/>

                     <div class="input-group input-group-lg width-full">
                        <label class="control-label">Biography or Personal Message</label>
                        {{ form.bio_message(class='form-control', id='editor1', placeholder='Tell us a bit about yourself and why you want to be a BFCT') }} 
                        {% if form.bio_message.errors %}
                            <ul class="danger list-margin-none list-bullets-none padding-left-0 text-align-right">
                                {% for error in form.bio_message.errors %}<li>{{ error }}</li>{% endfor %}
                            </ul>
                        {% endif %}
                     </div>

                    <hr/>

                    <button class="btn btn-default btn-success btn-squishy width-half pull-right margin-top-2" type="submit" value="Go">
                        Send Application <i class="fa fa-send"></i>
                    </button>
                </fieldset>
            </form>
            <div class="clearfix margin-top-2"></div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="box">
            <i class="backicon fa fa-question-circle"></i>
            <h2>What happens when I apply?</h2>
            <p>
                Once we receive your application, the Blender Foundation Certification Board
                will proceed to review it. This may take some days.
                <br/><br/>You can come back to this page and check
                the status of your application anytime.
                <br/><br/>Once your application has been reviewed, you'll receive
                an e-mail with the results, and instructions on how to proceed.
            </p>
        </div>
    </div>
</div>


{% endblock %}

{% block footer_scripts %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/ckeditor/4.0.1/ckeditor.js"></script>
    <script type="text/javascript">
    CKEDITOR.replace( 'editor1', {
        removePlugins: 'toolbar, elementspath',
        allowedContent: 'p h1 h2 strong em; a[!href];',
    });
    </script>

{% endblock %}

blender-bfct/application/templates/become_a_trainer.html
{% extends 'layout.html' %}
{% block page_title %}Become a Trainer{% endblock %}
{% block body %}
<div class="row">
	<div class="col-md-6">
			<div class="box">
		<h2>How to become a BFCT?</h2>
		<p>Based on a successful completion of fulfilling the selection criteria you can become a trainer for a period of one year. The trainer will then become an official "Blender Foundation Certified Trainer" (BFCT). The costs for becoming a BFCT for one year are euro 50,-. The BFCT is valid for one year.</p>
		
		<h2>Language</h2>
		<p>The Blender Institute encourages applicants from any and all linguistic backgrounds. Multi-language support is indeed a vital part of supporting the use of Blender everywhere. Nonetheless, as the language of the Blender Institute and the Blender educational review board is English; the board requires that a letter of interest and summary of professional experience be submitted in English. It is the applicant's responsibility to secure translation if they do not personally possess the necessary English skills to produce such a document. Additionally, the review board thanks non-English language applicants for their patience as supporting materials submitted in another language may require more time to be properly reviewed.</p>
		
		<h2>Proof of your Certification</h2>
		<p>Upon successful completion of fulfilling the selection criteria, you will hold the title of an official recognized Blender Foundation Certified Trainer for a period of one year. Once accepted you will <a href="http://www.blendernetwork.org/subscriptions" target="_blank">create a profile page</a> on the Blender Network. The fee for becoming a BFCT is €50 per year, which is the same amount as for a Freelance membership on the Blender Network, if you rather have a different membership type you can get in touch with the <a href="http://www.blendernetwork.org/contact" target="_blank">Network support</a>.</p>

		<p>As proof of the validity of the certification, the trainer's profile on the Blender Network will have a special "BFCT" tag for the duration of his/her certification.</p>

		<p>A certified trainer cannot give BFCT status to people who have attended their classes, however they are fully free to define their own courses or own student certification programs.</p>

		<p>At the end of the year as a certified trainer, individuals will be offered the opportunity to renew their certification. As part of the renewal process, they will be re-evaluated to assure that they are up to date with the most recent changes and additions to Blender.</p>

		<p>Please note, also, that this first year of the Blender Certified Trainer Program will be under evaluation as well. On the anniversary of the launch of the program, the review board may or may not make changes to the program in an effort ot improve it. The feedback and suggestions of those who go through this process would be greatly appreciated by the review board.</p>
		
		<h2>Contact for additional information</h2>
		<p>If you still like to know more about our program, you can join the <a href="http://lists.blender.org/mailman/listinfo/bf-education" target="_blank">mailing list bf-education</a> to ask questions.</p>

		<p>Or for more information of BFCT submissions, contact the board at: bfct-submissions at blender.org</p>
		</div>
	</div>
	<div class="col-md-6">
		<div class="box">
			<h2>Essential criteria for BFCT</h2>
			<p>Individuals who are interested in becoming an official Blender Foundation Certified Trainer must submit an online application to show that they meet the following criteria:</p>
			<h4>I. Proficiency in Blender</h4>
			<p>Candidates should know the purpose and function of the Blender Foundation and the Blender Insitute.</p>
			<p>Candidates should know Blender's history, how it became open source, and what being open source means to Blender's development and documentation.
			With a portfolio/reel submission consisting of stills, animations, and/or .blend files, candidates should exhibit proficiency in 7 of these core areas:</p>
			<ul class="list-margin-none">
				<li>Modeling</li>
				<li>Materials/Texturing</li>
				<li>Rigging</li>
				<li>Animation</li>
				<li>Compositing</li>
				<li>Lighting</li>
				<li>Scripting</li>
				<li>Rendering (internal/external)</li>
				<li>Dynamics/Simulation (fluids, particles, softbodies, etc.)</li>
				<li>Pipeline integration</li>
			</ul>
			<h4>II. Teaching Blender</h4>
			<p>With the submission of two examples of teaching, one written (written tutorial, book, etc.) and one by video (video tutorials, live classroom videos, etc.), a candidate should exhibit an ability to do the following things:</p>

			<p>Clearly explain methods and concepts to students.
			Understand the experience level of the students (clearly indicate if the teaching sample is for beginners, intermediate students, or advanced users and speak at their level).<br>
			Produce additional teaching material (diagrams, etc.) for complex subjects that require it.</p>
			<h4>III. Teaching Experience</h4>
			<p>Candidates should be at least 16 years old.
			With the submission of a resume or CV, a candidate should exhibit experience as an educator or trainer in at least one of the three following ways:</p>
			<ul class="list-margin-none">
				<li>Academic instructor</li>
				<li>Commercial trainer</li>
				<li>Community experience (includes forum assistance on blender forums, IRC support, community workshops, or updates to the Blender documentation wiki)</li>
			</ul>
			<p>A certified trainer should target at least one of the following audiences:</p>
			<ul class="list-margin-none">
				<li>Corporations who want employees trained in Blender</li>
				<li>School/College/University teachers who want to integrate Blender in classes</li>
				<li>Individual 3D artists who want to become trained in Blender</li>
			</ul>
			<p>Of the 9 members of the Blender Certification Review Board, at least 7 must approve of a candidate by agreeing that he or she meets the before mentioned criteria. Upon review, the board will pass its recommendation to the Blender Foundation and the candidate will be notified of the result with a short written explanation of the board's decision.</p>
		</div>
	</div>
</div>
<div class="row">
	<hr>
	<div class="col-md-8 col-md-offset-2">
		<div class="box text-center">
			<h2>Ready?</h2>
			<p>If you think you fulfill the requirements listed above, then you're ready to apply! In order to acces the form you need to have a Blender-ID. Don't have one yet? Get your Blender-ID <a href="https://www.blender.org/id">here</a>.</p>
			<p>
				<a class="btn btn-success btn-squishy width-half" href="{{url_for('apply')}}">Apply for BFCT</a>
			</p>
		</div>
	</div>
</div>

{% endblock %}

blender-bfct/application/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block page_title %}Home{% endblock %} - Blender Foundation Certified Trainer - blender.org</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <!-- <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'> -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='assets_shared/css/generic.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='assets/css/main.css') }}" rel="stylesheet">

<!--     <link rel="stylesheet" type="text/css" href="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/css/jquery.dataTables.css"> -->

    <!-- IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='assets_shared/images/favicon.ico') }}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="apple-touch-icon-57-precomposed.png">
    {% block header %}
    {% endblock %}
  </head>

  <body class="transition-none">
    {% block modal %}
    {% endblock %}
    <a name="hop"></a>

    <header class="navbar navbar-default navbar-fixed-top bright" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-menu">
            <span class="sr-only">Toggle navigation</span>
            <i class="fa fa-bars"></i>
          </button>
          <a class="logo" href="http://www.blender.org"></a>
        </div>

        <nav class="collapse navbar-collapse" id="navbar-collapse-menu">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="http://www.blender.org/features/">Features</a></li>
                <li><a href="http://www.blender.org/download/">Download</a></li>
                <li><a href="http://www.blender.org/support/">Support</a></li>
                <li><a href="http://www.blender.org/get-involved/">Get Involved</a></li>
                <li><a href="http://www.blender.org/about/">About</a></li>
                <li><a href="http://www.blender3d.org/e-shop/">Store</a></li>
            </ul>
        </nav>
      </div>
    </header>

    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
      <div class="container">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert"><i class="fa fa-times"></i></button>
      </div>
    </div>
    {% endfor %}

  <div class="container-main">
    <div class="container-fluid featured featured-xs">
      <div class="col-md-12">
        <div class="container">
          <i class="backicon bf-network"></i>
          <h1>Blender Foundation Certified Trainer Program</h1>
        </div>
      </div>
    </div>

    <header class="navbar navbar-default navbar-secondlevel navbar-static-top bright" role="navigation">
      <div class="container relative">
        <ul class="nav navbar-nav navbar-left">
          <li {% if title == 'home': %} class="active"{% endif %}>
            <a href="{{ url_for('homepage') }}">About</a>
          </li>
          <li {% if title == 'become_a_trainer': %} class="active"{% endif %}>
            <a href="{{ url_for('become_a_trainer') }}">Become a Trainer</a>
          </li>
          {% if (current_user.has_role('bfct_board') or current_user.has_role('bfct_manager') )%}
          <li {% if title == 'applications': %} class="active"{% endif %}>
            <a href="{{url_for('applications.index')}}">Review Applications</a>
          </li>
          {% endif %}

          {% if current_user.is_authenticated() %}
          <li class="dropdown absolute right">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{current_user.email}} <b class="caret"></b></a>
            <ul class="dropdown-menu right">
              {% if not current_user.has_role('bfct') %}
              <li><a href="{{url_for('apply')}}"><i class="fa fa-edit"></i> Apply / View</a></li>
              {% endif %}
              <li class="divider"></li>
              <li><a href="{{url_for_security('logout', next='/certification')}}"><i class="fa fa-power-off"></i> Log out</a></li>
            </ul>
          </li>
          {% else %}
          <li class="absolute right"><a href="{{url_for_security('login', next='/certification')}}"><i class="fa fa-sign-in"></i> Sign in</a></li>
          {% endif %}
        </ul>
      </div>
    </header> <!-- // second level-->

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          {% block body %}{% endblock %}
        </div>
      </div>
    </div> <!-- /container -->
  </div> <!-- /container-main -->

    <div id="footer-navigation"> <!-- Sitemap -->
      <div class="container">
        <div class="row">
          <div class="col-md-3 col-xs-6 margin-top-1">
            <h4>Blender</h4>
            <ul>
              <a href="http://www.blender.org/download/" title="Download Blender">
                <li>Download</li>
              </a>
              <a href="http://www.blender.org/download/" title="Source Code">
                <li>Source Code</li>
              </a>
              <a href="http://www.blender.org/features/" title="Blender Features">
                <li>Features</li>
              </a>
              <a href="http://wiki.blender.org/index.php/Doc:2.6/Manual" title="Blender Documentation">
                <li>Documentation</li>
              </a>
            </ul>
          </div>
          <div class="col-md-3 col-xs-6 margin-top-1">
            <h4>Organization</h4>
            <ul>
              <a href="http://www.blender.org/foundation/" title="Blender Foundation">
                <li>Foundation</li>
              </a>
              <a href="http://www.blender.org/institute/" title="Blender Institute">
                <li>Institute</li>
              </a>
              <a href="http://www.blender.org/get-involved/developers/" title="Developers">
                <li>Developers</li>
              </a>
              <a href="http://www.blendernetwork.org"
              title="The Network of Blender Professionals">
                <li><i class="bf-network"></i> Blender Network</li>
              </a>
            </ul>
          </div>
          <div class="col-md-3 col-xs-6 margin-top-1">
            <h4>Get Involved</h4>
            <ul>
              <a href="http://www.blender.org/foundation/donation-payment/" title="Donations">
                <li>Donations</li>
              </a>
              <a href="http://www.blender.org/get-involved/developers/" title="Software">
                <li>Software</li>
              </a>
              <a href="http://www.blender.org/get-involved/" title="Websites and Docs">
                <li>Websites & Docs</li>
              </a>
              <a href="http://www.blender.org/conference/" title="Conferences">
                <li>Conferences</li>
              </a>
            </ul>
          </div>
          <div class="col-md-3 col-xs-12 margin-top-1">
            <h4>Blender.org</h4>
            <ul>
              <a href="http://www.blender.org/news/" title="News">
                <li>News</li>
              </a>
              <a href="http://www.blender.org/foundation/" title="Contact">
                <li>Contact</li>
              </a>
              <a href="http://www.blender.org/about/logo/" title="Trademark and Logo">
                <li>Trademark & Logo</li>
              </a>
              <a href="http://www.blender.org/about/website/" title="Website License">
                <li>Website License</li>
              </a>
            </ul>
          </div>
        </div> <!-- footer row -->
      </div> <!-- footer container -->
    </div> <!-- footer-navigation -->

    <footer>
      <div class="container">
        <span class="pull-right">
          <p>
            Blender.org
            <a href="#hop"><i class="fa fa-angle-up"></i></a>
          </p>
        </span>
      </div> <!-- /footer-container -->
    </footer>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script type="text/javascript">$(window).load(function() {$("body").removeAttr("class"); /* Avoid transitions jump on load */});</script>
  {% block footer_scripts %}{% endblock %}


  </body>
</html>